### PR TITLE
fix(fresh_dio): onResponse response is null case

### LINKED ISSUE #23: Exception on non-response Dio error
Hello,

Thank you for writing this package, so far it works great for me.

I have found a minor issue using it with Dio: When an error occurs during the request Fresh checks the response object whether it should refresh, specifically `response.statusCode`. However the `response` object can be `null` thus causing `noSuchMethod`.
Checking the dio_error.dart file:

```dart
/// Response info, it may be `null` if the request can't reach to
/// the http server, for example, occurring a dns error, network is not available.
Response response;
```

In my case it also occured during a connection timeout error. This will cause the original `DioError.CONNECT_TIMEOUT` to be changed to `DioErrorType.DEFAULT` so it will result in a different error type caught in the code when I want to display a timeout message.

A simple null aware change could make it work like intended I think. Adding the question mark to fresh.dart:148.

```dart
static bool _defaultShouldRefresh(Response response) {
  return response?.statusCode == 401;
}
```

Full exception log:
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Fresh._defaultShouldRefresh (package:fresh_dio/src/fresh.dart:148:21)
#2      Fresh.onError (package:fresh_dio/src/fresh.dart:110:42)
#3      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart:867:40)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
#7      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#8      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#9      Future._completeError (dart:async/future_impl.dart:537:5)
#10     _SyncCompleter._completeError (dart:async/future_impl.dart:59:12)
#11     _Completer.completeError (dart:async/future_impl.dart:31:5)
#12     Future.any.onError (dart:async/future.dart:476:45)
#13     _rootRunBinary (dart:async/zone.dart:1214:47)
#14     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#15     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#16     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#17     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#18     Future._completeError (dart:async/future_impl.dart:537:5)
#19     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#20     DioMixin._dispatchRequest (package:dio/src/dio.dart)
<asynchronous suspension>
#21     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#22     DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
#23     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
#24     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#25     _rootRun (dart:async/zone.dart:1182:47)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#32     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

fresh version: 0.2.1
fresh_dio version: 0.1.1
dio version: 3.0.9

I could also submit a pull request if you want. Please let me know what you think.

### PR DESCRIPTION
**Pull request by dricholm**
This fixes #23 

Please let me know if there are any comments.

I also noticed running `pub run test_coverage` generates a `coverage_badge.svg` in the `packages/*` folder. This is not included in `.gitignore` right now, but I don't see it used anywhere now so I did not commit it. Maybe this could also be added to the root `.gitignore`? If you want I can also add another commit to update the `.gitignore`.

Thank you!

### CODE REVIEW

File: packages/fresh_dio/lib/src/fresh.dart [hunk 1]
```diff
@@ -145,7 +145,7 @@ class Fresh<T extends Token> extends Interceptor {
   }
 
   static bool _defaultShouldRefresh(Response response) {
-    return response.statusCode == 401;
+    return response != null && response.statusCode == 401;
```
Comment (felangel) [inline packages/fresh_dio/lib/src/fresh.dart:148]:
```suggestion
    return response?.statusCode == 401;
```

**Comment by felangel** [comment]
> This fixes #23
> 
> Please let me know if there are any comments.
> 
> I also noticed running `pub run test_coverage` generates a `coverage_badge.svg` in the `packages/*` folder. This is not included in `.gitignore` right now, but I don't see it used anywhere now so I did not commit it. Maybe this could also be added to the root `.gitignore`? If you want I can also add another commit to update the `.gitignore`.
> 
> Thank you!

The coverage badge is intentionally not ignored because it is referenced in the README 👍

**Comment by felangel** [comment]
Published the fix in `fresh_dio 0.1.3` 🎉
